# myApp/docker-compose.yaml
version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '80:80'
    depends_on:
      - bff
  bff:
    build: ./bff
    container_name: bff_c
    ports:
      - '3000:3000'